spring:
  application:
    name: passive-operations-service
  cloud:
    config:
      uri: http://20.83.138.240:8888
      username: root
      password: p1a2s3s
  config:
    import: optional:configserver:http://20.83.138.240:8888